config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
    },
    path_names: {
      sign_in: 'connexion',
      sign_out: 'deconnexion',
    },
    path: 'auth'

  mount Sidekiq::Web => '/sidekiq'

  root to: 'projects#index'

  namespace :api do
    resources :users, only: :index
    resources :projects, path: 'projets' do
      resources :assignments, only: [:index, :create, :destroy], path: 'membres'
      get 'assignable-users', to: 'assignments#assignable_users'
    end
  end

  resources :users,
    path: 'utilisateurs',
    path_names: { new: 'creer', edit: 'editer' } do
      resource :impersonation, only: [:create, :destroy], module: :users
    end

  resources :companies, path: 'groupes', path_names: { new: 'creer', edit: 'editer' }, except: :destroy do
    resources :employments, only: [:index, :create, :destroy], path: 'membres'
  end

  resources :projects, path: 'projets', path_names: { new: 'creer', edit: 'editer' } do
    resources :assignments, only: :index, path: 'membres'
    resources :folders, path: 'dossiers'
    resources :subscriptions
  end

  resources :documents
  resources :archives, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :documents, dependent: :destroy

  validates :name, presence: true
  validate :name_is_unique_inside_parent_folder

  has_ancestry

  def has_content?
    documents.exists? || children.exists?
  end

  def name_is_unique_inside_parent_folder
    if siblings.pluck(:name).include?(name)
      errors.add(:name, "indisponible. Merci d'en choisir un autre.")
    end
  end

  def contains_only_resources_owned_by_user?(user)
    subtree.all? do |folder|
       folder.owned_by_user?(user) &&
       folder.documents.all? { |document| document.owned_by_user?(user) }
    end
  end

  def owned_by_user?(user)
    user_id == user.id
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def show
    @project = Project.find(params[:project_id])
    @subscription = Subscription.find_by(subscribeable_type: "Project",
                                       subscribeable_id: @project,
                                       subscriber: current_user)
    @folder = Folder.find(params[:id])
    @child_folder = Folder.new
  end

  def create
    @project = Project.find(params[:project_id])
    @folder = Folder.find(params[:id])
    @child_folder = current_user.folders.build(
      name: folder_params[:name],
      user: current_user,
      project: @project,
      parent: @folder
    )

    if @child_folder.save
      redirect_to project_folder_path(@project, @folder), notice: 'Dossier créé avec succès.'
    else
      render :show
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @folder = Folder.find(params[:id])
  end

  def update
    folder = current_resource

     if folder.update(folder_params)
       redirect_to project_folder_path(folder.project, folder.parent), notice: 'Dossier déplacé avec succès'
     else
       render :edit
     end
  end

  def destroy
    project = Project.find(params[:project_id])
    folder = Folder.find(params[:id])
    parent_folder = folder.parent

    folder.destroy
    redirect_to project_folder_path(project, parent_folder), notice: 'Dossier supprimé avec succès.'
  end

  private

  def folder_params
    params.require(:folder).permit(:name, :parent_id)
  end

  def current_resource
    @current_resource ||= Folder.find(params[:id]) if params[:id]
  end
end

app/views/folders/_breadcrumbs.html.erb
<nav class="bg-grey-lightest p-3 rounded w-full text-sm">
  <ul class="list-reset flex text-grey-dark">
    <% @folder.ancestors.each do |folder| %>
      <li class="text-blue font-bold">
        <%= link_to folder.name, project_folder_path(@project, folder) %>
      </li>
      <li><span class="mx-2">/</span></li>
    <% end %>
    <li>
      <%= @folder.name %>
    </li>
  </ul>
</nav>

app/views/folders/_document_upload_form.html.erb
<%= form_with(model: Document.new, local: true) do |f| %>
  <%= f.hidden_field :folder_id, value: @folder.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.file_field :file, direct_upload: true %>
  <%= f.button type: :submit, class: "button" do %>
    <span class="file-icon">
      <i class="fas fa-upload"></i>
    </span>
    <span>Déposer</span>
  <% end %>
<% end %>

app/views/folders/_folder_content_item.html.erb
<div class="flex text-sm mb-4">
  <div class="w-1/3">
    <i class="w-4 h-4 mr-2 far fa-folder"></i>
    <%= link_to folder.name, project_folder_path(@project, folder) %>
  </div>

  <div class="w-1/6">
    -
  </div>

  <div class="w-1/6">
    <%= folder.user.full_name %>
  </div>

  <div class="w-1/6">
    -
  </div>

  <div class="w-1/6">
    Dossier
  </div>

  <div class="w-1/6">
    <% if allow_action? :folders, :edit, folder %>
      <%= link_to "Déplacer vers ...", edit_project_folder_path(@project, folder), title: "Déplacer ce dossier", class: "text-xs" %>
    <% end %>
  </div>

  <div class="w-1/6">
    <% if allow_action? :folders, :destroy, folder %>
      <%= button_to "Supprimer", project_folder_path(@project, folder), method: :delete, title: "Supprimer ce dossier", class: "text-xs text-red underline" %>
    <% end %>
  </div>
</div>

app/views/folders/_folder_contents.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Nom</th>
      <th>Déposé le</th>
      <th>Propriétaire</th>
      <th>Taille</th>
      <th>Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @folder.children.exists? %>
      <% @folder.children.each do |folder| %>
        <tr>
          <td class="is-narrow">
            <span class="icon">
              <i class="far fa-folder"></i>
            </span>
          </td>
          <td><%= link_to folder.name, project_folder_path(@project, folder) %></td>
          <td>-</td>
          <td><%= folder.user.full_name %></td>
          <td>-</td>
          <td>Dossier</td>
          <td class="is-narrow">
            <% if allow_action? :folders, :edit, folder %>
              <%= link_to "Déplacer vers ...", edit_project_folder_path(@project, folder), title: "Déplacer ce dossier", class: "button is-small is-info" %>
            <% end %>
          </td>
          <td class="is-narrow">
            <% if allow_action? :folders, :destroy, folder %>
              <%= button_to "Supprimer", project_folder_path(@project, folder), method: :delete, title: "Supprimer ce dossier", class: "button is-small is-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>

    <% if @folder.documents.exists? %>
      <% @folder.documents.each do |document| %>
        <tr>
          <td class="is-narrow">
            <span class="icon">
              <i class="far fa-file"></i>
            </span>
          </td>
          <td>
            <%= link_to document.file.filename, rails_blob_path(document.file, disposition: "attachment") %>
          </td>
          <td>
            <%= document.created_at.strftime("%d %b %Y à %H:%M") %>
          </td>
          <td>
            <%= document.user.full_name %>
          </td>
          <td>
            <%= number_to_human_size(document.file.byte_size, precision: 2, separator: ',') %>
          </td>
          <td>
            <%= document.file.content_type %>
          </td>
          <td class="is-narrow">
            <% if allow_action? :documents, :edit, document %>
              <%= link_to "Déplacer vers ...", edit_document_path(document), title: "Déplacer ce document", class: "button is-small is-info" %>
            <% end %>
          </td>
          <td class="is-narrow">
            <% if allow_action? :documents, :destroy, document %>
              <%= button_to "Supprimer", document, method: :delete, title: "Supprimer ce document", class: "button is-small is-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/folders/_folder_creation_form.html.erb
<%= form_with(model: [@project, @child_folder], local: true, class: "w-full max-w-sm") do |f| %>
  <div class="flex items-center border-b border-b-2 border-blue py-2">
    <%= f.text_field :name, class: "appearance-none bg-transparent border-none w-full text-grey-darker mr-3 py-1 px-2 leading-tight focus:outline-none #{"color-red" if @child_folder.errors.any?}", placeholder: "Nom de dossier" %>

    <%= hidden_field_tag :id, @folder.id %>

    <%= f.submit 'Créer', class: "flex-no-shrink bg-blue hover:bg-blue-dark border-blue hover:border-blue-dark text-sm border-4 text-white py-1 px-2 rounded" %>
  </div>
<% end %>

app/views/folders/_form.html.erb
<%= form_with(model: folder, local: true) do |form| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "erreur", "erreurs") %>:</h2>

      <ul>
        <% folder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, 'Nom' %>
    <%= form.text_field :name %>
    <%= form.submit action_name == 'new' ? 'Créer' : 'Valider' %>
  </div>
<% end %>

app/views/folders/_tree.html.erb
<ul>
  <% node.subtree.arrange.each do |parent, child| %>
    <% parent.children.each do |folder| %>
      <% unless folder.id == current_folder.id %>
          <%= form.radio_button(:parent_id, folder.id, checked: folder.id == current_folder.parent_id) %>
          <span class="icon">
            <i class="far fa-folder"></i>
          </span>
          <%= folder.name %>
      <% end %>
      <%= render 'tree', node: folder, current_folder: current_folder, form: form %>
    <% end %>
  <% end %>
</ul>

app/views/folders/edit.html.erb
<section class="section">
  <div class="container">
    <%= render 'breadcrumbs' %>

    <% if allow_action? :folders, :edit, @folder %>
      <div class="content">
        <h3 class="title is-4">
          Deplacer le dossier <em><%= @folder.name %></em> vers ...
        </h3>

        <%= form_with(model: [@project, @folder], local: true) do |form| %>
          <div class="field">
            <div class="control">
              <% @folder.errors.full_messages.each do |message| %>
                <p class="help is-danger"><%= message %></p>
              <% end %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= render 'tree', node: @folder.root, current_folder: @folder, form: form %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= form.submit 'Deplacer', class: "button is-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/folders/new.html.erb
<h1>Nouveau dossier</h1>

<%= render 'form', folder: @folder %>

app/views/folders/show.html.erb
<%= component("page") do %>
  <%= component("project") %>
<% end %>