config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
    },
    path_names: {
      sign_in: 'connexion',
      sign_out: 'deconnexion',
    },
    path: 'auth'

  mount Sidekiq::Web => '/sidekiq'

  root to: 'projects#index'

  namespace :api do
    resources :users, only: :index
    resources :projects, path: 'projets' do
      resources :assignments, only: [:index, :create, :destroy], path: 'membres'
      get 'assignable-users', to: 'assignments#assignable_users'
    end
  end

  resources :users,
    path: 'utilisateurs',
    path_names: { new: 'creer', edit: 'editer' } do
      resource :impersonation, only: [:create, :destroy], module: :users
    end

  resources :companies, path: 'groupes', path_names: { new: 'creer', edit: 'editer' }, except: :destroy do
    resources :employments, only: [:index, :create, :destroy], path: 'membres'
  end

  resources :projects, path: 'projets', path_names: { new: 'creer', edit: 'editer' } do
    resources :assignments, only: :index, path: 'membres'
    resources :folders, path: 'dossiers'
    resources :subscriptions
  end

  resources :documents
  resources :archives, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :users, through: :assignments
  has_many :subscriptions, as: :subscribeable
  has_many :subscribers, through: :subscriptions

  has_one :root_folder, ->{ where(ancestry: nil) }, class_name: "Folder", dependent: :destroy

  validates :name, presence: true

  enum status: [ :active, :archived ]

  scope :active,   ->{ where(status: "active") }
  scope :archived, ->{ where(status: "archived") }

  def self.default_scope
    order('name ASC')
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < Api::ApiController
  def index
    projects = Project.where("name ILIKE ?", "%#{params[:query]}%")
    render json: projects
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = show_all_projects? ? Project.active.includes(:subscriptions) : current_user.projects.active.includes(:subscriptions)
  end

  def show
    redirect_to project_folder_path(current_resource, current_resource.root_folder)
  end

  def new
    @project = Project.new
  end

  def create
    project = Project.new(project_params)
    folder = Folder.new(
      name: "#{project.name}",
      project: project,
      user: current_user
    )

    ActiveRecord::Base.transaction do
      project.save!
      folder.save!
    end

    redirect_to projects_url, notice: 'Projet créé avec succès.'
  end

  def edit
    @project = current_resource
  end

  def update
    project = current_resource

    if project.update(project_params)
      project.root_folder.update(name: project.name)
      redirect_to projects_url, notice: 'Modifications enregistrées.'
    else
      render :edit
    end
  end

  def destroy
    project = current_resource
    project.destroy
    redirect_to projects_url, notice: "Projet #{project.name} supprimé."
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def current_resource
    @current_resource ||= Project.find(params[:id]) if params[:id]
  end

  def show_all_projects?
    current_user.admin? || current_user.employee?
  end
end

app/views/projects/_controls.html.erb
<div class="columns">
  <div class="column">
    <% if subscription.present? %>
      <%= button_to project_subscription_url(project, subscription), class: "button is-small", method: :delete do %>
        <span class="icon is-small has-text-danger">
          <i class="fas fa-users"></i>
        </span>
        <span>Arrêter de suivre</span>
      <% end %>
    <% else %>
      <%= button_to project_subscriptions_url(project), class: "button is-small", method: :post do %>
        <span class="icon is-small has-text-success">
          <i class="fas fa-users"></i>
        </span>
        <span>Suivre</span>
      <% end %>
    <% end %>
  </div>

  <div class="column">
    <% if allow_action? :projects, :edit %>
      <%= link_to "Editer", edit_project_url(project), class: "button is-small" %>
    <% end %>
  </div>

  <div class="column">
    <% if allow_action? :assignments, :create %>
      <%= link_to "Gérer les membres", project_assignments_path(project), class: "button is-small" %>
    <% end %>
  </div>

  <div class="column">
    <% if project.active? %>
      <% if allow_action? :archives, :create %>
        <%= button_to "Archiver", archives_path(project_id: project.id), method: :post, class: "button is-small" %>
      <% end %>
    <% end %>

    <% if project.archived? %>
      <% if allow_action? :archives, :destroy %>
        <%= button_to "Désarchiver", archive_path(project.id), method: :delete, class: "button is-small" %>
      <% end %>
    <% end %>
  </div>

  <div class="column">
    <% if allow_action? :projects, :delete %>
      <%= button_to "Supprimer", project, method: :delete, class: "button is-small is-danger" %>
    <% end %>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, class: "w-full") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "erreur", "erreurs") %>:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/8">
      <%= form.label :name, 'Nom', class: "block text-grey mb-1 md:mb-0 pr-4" %>
    </div>

    <div class="md:w-1/3 mr-4">
      <%= form.text_field :name, class: "bg-grey-lighter appearance-none border-2 border-grey-lighter rounded w-full py-2 px-4 text-grey-darker leading-tight focus:outline-none focus:bg-white focus:border-blue", autofocus: true %>
    </div>

    <div class="md:w-1/3">
      <%= form.submit action_name == 'new' ? 'Créer' : 'Valider', class: "shadow bg-blue hover:bg-blue-light focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h2>Editer le projet '<%= @project.name %>'</h2>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<%= component("page") do %>
  <%= component("projects") %>
<% end %>

app/views/projects/new.html.erb
<%= tag.h1 'Créer un nouveau projet', class: "py-6" %>

<%= render 'form', project: @project %>