config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
    },
    path_names: {
      sign_in: 'connexion',
      sign_out: 'deconnexion',
    },
    path: 'auth'

  mount Sidekiq::Web => '/sidekiq'

  root to: 'projects#index'

  namespace :api do
    resources :users, only: :index
    resources :projects, path: 'projets' do
      resources :assignments, only: [:index, :create, :destroy], path: 'membres'
      get 'assignable-users', to: 'assignments#assignable_users'
    end
  end

  resources :users,
    path: 'utilisateurs',
    path_names: { new: 'creer', edit: 'editer' } do
      resource :impersonation, only: [:create, :destroy], module: :users
    end

  resources :companies, path: 'groupes', path_names: { new: 'creer', edit: 'editer' }, except: :destroy do
    resources :employments, only: [:index, :create, :destroy], path: 'membres'
  end

  resources :projects, path: 'projets', path_names: { new: 'creer', edit: 'editer' } do
    resources :assignments, only: :index, path: 'membres'
    resources :folders, path: 'dossiers'
    resources :subscriptions
  end

  resources :documents
  resources :archives, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true

  def self.default_scope
    order('name ASC')
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = current_resource
  end

  def new
    @company = Company.new
  end

  def create
    company = Company.new(company_params)

    if company.save
      redirect_to company, notice: 'Groupe créé avec succès.'
    else
      render :new
    end
  end

  def edit
    @company = current_resource
  end

  def update
    company = current_resource

    if company.update(company_params)
      redirect_to company, notice: 'Modifications enregistrées.'
    else
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end

  def current_resource
    @current_resource ||= Company.find(params[:id]) if params[:id]
  end
end

app/views/companies/_controls.html.erb
<% if allow_action? :companies, :edit %>
  <%= link_to "Editer", edit_company_url(company), class: "button is-small" %>
<% end %>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "erreur", "erreurs") %>:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nom', class: "label" %>
    <div class="control">
      <%= form.text_field :name, autofocus: true, class: "input" %>
    </div>
  </div>

  <div class="control">
    <%= form.submit action_name == 'new' ? 'Créer' : 'Valider', class: "button is-primary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-2">Editer le groupe '<%= @company.name %>'</h2>

    <%= render 'form', company: @company %>
  </div>
</section>

app/views/companies/index.html.erb
<h2 class="mb-8">Groupes</h2>

<div class="mb-8">
  <% if allow_action? :companies, :create %>
    <%= link_to 'Créer un nouveau groupe', new_company_url, class:"btn btn-blue" %>
  <% end %>
</div>

<div class="flex flex-wrap">
  <% @companies.each do |company| %>
    <div class="w-1/5 rounded overflow-hidden shadow mr-4 mb-4">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2"><%= link_to company.name, company %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/new.html.erb
<%= tag.h2 'Créer un nouveau groupe', class: "mb-8" %>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<section class="section">
  <div class="container">
    <%= tag.h2 @company.name, class: "title is-2" %>

    <div class="content">
      <%= render 'controls', company: @company %>

      <% if @company.users.any? %>
        <hr />

        <table class="table">
          <thead>
            <tr>
              <th>
                Nom
              </th>
              <th>
                Email
              </th>
              <th>
                Niveau d'accès
              </th>
              <th>
                Statut
              </th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @company.users.each do |user| %>
              <tr>
                <td><%= link_to user.full_name, user %></td>
                <td><%= user.email %></td>
                <td><%= t("activerecord.attributes.user.group.#{user.group}") %></td>
                <td><%= user.account_status %></td>
                <td>
                  <% if allow_action?(:users, :edit, user) %>
                    <%= link_to "Editer", edit_user_url(user), class: "button is-small" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</section>